# Generated by Django 4.2.3 on 2023-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_rename_post_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="tourism",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="website",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
