# Generated by Django 4.2.3 on 2023-07-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_location_email_location_phone_location_tourism_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
