# Generated by Django 4.2.3 on 2023-07-11 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maps", "0005_rating_image_location_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="ratings",
            field=models.ManyToManyField(
                default=0,
                related_name="locations",
                through="maps.Rating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
